# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 903e71a6a4759d4e1f5f10f1b10362f5b8d2594c2556bf4bb2aafc60635006eddbbfac27934e473ea0f2ddabdc7cc6db2c28fca472457280602c327edff240f7

test:
  secret_key_base: fc2521949e5bbea1a62f0a7317e491a9a9e38280060a3a12abec31ed5c001d7abd3ebcda31095227f13e5cb8e05cfa9a8702cf8e8d797521fc07273e8250cf08

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>